services:
  database:
    image: postgres:13.16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: chief
      POSTGRES_PASSWORD: root
      POSTGRES_DB: chief
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chief -d chief"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: spring_app
    depends_on:
      database:
        condition: service_healthy
      kafka:
        condition: service_started
    ports:
      - '8080:8080'
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=chief
      - DB_USER=chief
      - DB_PASSWORD=root
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_INITIALIZATION_MODE=always
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092


  zookeeper:
      image: confluentinc/cp-zookeeper:latest
      container_name: zookeeper
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000
      ports:
        - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
